name: CI
on: 
  - push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: t1
        uses: docker/build-push-action@v6
        with:
          context: "./alpine_3_20"
          build-args:
            - OPAM_VERSION=2.1.6
            - OCAML_VERSION=4.14.2
      - name: t2
        uses: docker/build-push-action@v6
        with:
          context: "./alpine_3_20"
          build-args:
            - OPAM_VERSION=2.2.0
            - OCAML_VERSION=4.14.2
            